import {useState} from 'react';
import type {Episode} from '../core/episodes';
import {NARRATIVE_LIMIT,NARRATIVE_LABELS} from '../core/narratives';
import type {Narrative,NarrativeKind} from '../core/narratives';
export default function NarrativesDrawer({entries,episodes,draft,generating,ready,error,onGenerate,onDraft,onSave,onDelete,onUse,onStop,onClose}:{entries:Narrative[];episodes:Episode[];draft:Narrative|null;generating:boolean;ready:boolean;error:string;onGenerate:(kind:NarrativeKind,ids:string[],previous?:Narrative)=>void;onDraft:(draft:Narrative|null)=>void;onSave:()=>void;onDelete:(id:string)=>void;onUse:(id:string,enabled:boolean)=>void;onStop:()=>void;onClose:()=>void}){
 const [kind,setKind]=useState<NarrativeKind>('theme'),[ids,setIds]=useState<string[]>([]),[query,setQuery]=useState('');
 return <><div className="scrim" onClick={onClose}/><section className="drawer" role="dialog" aria-label="Life themes, lessons and beliefs"><header className="drawer-head"><h2>Themes, lessons &amp; beliefs</h2><button className="btn" onClick={onClose}>Close</button></header><div className="drawer-body">
 <p>Choose up to four reviewed moments to draft a tentative interpretation. Review and edit before saving. Saving keeps interpretations separate from identity and relationship stats. Explicitly enable a saved version to use it in relevant replies. New versions start disabled.</p>
 <label className="field"><span>Draft type</span><select disabled={generating} value={kind} onChange={e=>setKind(e.target.value as NarrativeKind)}><option value="theme">Life theme</option><option value="lesson">Lesson</option><option value="belief">Belief interpretation</option></select></label>
 <h3>Reviewed evidence ({ids.length}/4 selected)</h3>{episodes.length===0&&<p>Save an episodic memory in Event history first.</p>}
 {episodes.map(e=><label className="field" key={e.id}><span><input type="checkbox" checked={ids.includes(e.id)} disabled={generating||!!draft||(!ids.includes(e.id)&&ids.length>=4)} onChange={v=>setIds(v.target.checked?[...ids,e.id]:ids.filter(id=>id!==e.id))}/>{e.content}</span><small>{e.source.outcome}</small></label>)}
 <button className="btn" disabled={!ready||generating||!!draft||!ids.length||entries.length>=NARRATIVE_LIMIT} onClick={()=>onGenerate(kind,ids)}>Draft interpretation</button>
 {generating&&<p role="status">Drafting… <button className="btn" onClick={onStop}>Stop</button></p>}{error&&<p role="alert" className="msg-error">{error}</p>}
 {draft&&<article className="memory-card"><h3>Review {NARRATIVE_LABELS[draft.kind]} · v{draft.version}</h3><label className="field"><span>Interpretation</span><textarea rows={5} maxLength={2000} disabled={generating} value={draft.content} onChange={e=>onDraft({...draft,content:e.target.value})}/></label><p className="hint-soft">Tentative interpretation of {draft.sources.length} selected moments.</p><button className="btn primary" disabled={!ready||generating||!draft.content.trim()||entries.length>=NARRATIVE_LIMIT} onClick={onSave}>Save reviewed interpretation</button><button className="btn" disabled={generating} onClick={()=>onDraft(null)}>Discard draft</button></article>}
 <h3>Saved interpretations ({entries.length}/{NARRATIVE_LIMIT})</h3><p className="hint-soft">Revisions keep the original. At the limit, delete an old version to make room; nothing is automatically pruned.</p><label className="field"><span>Search interpretations</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 {[...entries].reverse().filter(n=>n.content.toLowerCase().includes(query.trim().toLowerCase())).map(n=><article className="memory-card" key={n.id}><h3>{NARRATIVE_LABELS[n.kind]} · v{n.version}</h3><p className="memory-content">{n.content}</p><label className="check"><input type="checkbox" checked={n.useInChat===true} disabled={!ready||generating} onChange={e=>onUse(n.id,e.target.checked)}/>Use this interpretation in relevant replies</label><p className="hint-soft">Reviewed interpretation · {new Date(n.createdAt).toLocaleString()}</p>{n.parentId&&<p className="hint-soft">Revises {n.parentId}{entries.some(e=>e.id===n.parentId)?'':' (earlier version deleted)'}</p>}<details><summary>Recorded evidence ({n.sources.length} moments)</summary>{n.sources.map(s=><div key={s.id}><p><b>Reviewed note:</b> {s.content}</p><p><b>Recorded outcome:</b> {s.source.outcome}</p><p className="hint-soft">{s.source.title} · {new Date(s.source.recordedAt).toLocaleString()} · Event {s.source.eventId}</p></div>)}</details><button className="btn" disabled={!ready||generating||!!draft||entries.length>=NARRATIVE_LIMIT||n.version>=100} onClick={()=>onGenerate(n.kind,[],n)}>Draft revision</button><button className="btn" disabled={!ready||generating} onClick={()=>{if(window.confirm('Delete this interpretation version? Sources and other versions stay unchanged.'))onDelete(n.id);}}>Delete version</button></article>)}
 </div></section></>;
}
