import {SpeechEndpoint} from './handsFree';
import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {loadWhisper,saveWhisper,encodeWave,microphoneLevel} from './whisper';
import type {DictationReview} from './dictation';
import {dictationReview} from './dictation';
export function useWhisper(onReview:(review:DictationReview)=>void,names:string[]){
 const [settings,setSettings]=useState(loadWhisper),[phase,setPhase]=useState<'idle'|'starting'|'recording'|'transcribing'>('idle'),[error,setError]=useState('');
 const [elapsed,setElapsed]=useState(0),[level,setLevel]=useState(0);
 const meter=useRef({started:0,level:0});
 useEffect(()=>{if(phase!=='recording'){setElapsed(0);setLevel(0);return;}const tick=setInterval(()=>{setElapsed(Math.min(15,(performance.now()-meter.current.started)/1000));setLevel(meter.current.level);},100);return ()=>clearInterval(tick);},[phase]);
 const nativePending=useRef(false);
 const token=useRef(0),capture=useRef<{stream:MediaStream;context:AudioContext;source:MediaStreamAudioSourceNode;node:ScriptProcessorNode;chunks:Float32Array[];count:number}|null>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),pollTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),callback=useRef(onReview);callback.current=onReview;
 function release(){clearTimeout(timer.current);const c=capture.current;capture.current=null;if(c){c.node.onaudioprocess=null;c.node.disconnect();c.source.disconnect();c.stream.getTracks().forEach(track=>track.stop());void c.context.close();}return c;}
 async function cancel(){token.current++;release();clearTimeout(pollTimer.current);if(!nativePending.current)setPhase('idle');await invoke('whisper_stop').catch(e=>setError(String(e)));}
 useEffect(()=>()=>{token.current++;release();clearTimeout(pollTimer.current);void invoke('whisper_stop').catch(()=>{});},[]);
 async function poll(id:number){if(id!==token.current)return;try{const result=await invoke<{done:boolean;text?:string;error?:string}>('whisper_poll');if(id!==token.current)return;if(result.done){setPhase('idle');if(result.error)setError(result.error);else callback.current(dictationReview(result));}else pollTimer.current=setTimeout(()=>void poll(id),300);}catch(e){if(id===token.current){setPhase('idle');setError(String(e));}void invoke('whisper_stop').catch(()=>{});}}
 async function finish(){const id=token.current,c=release();if(!c)return;setPhase('transcribing');try{const samples=new Float32Array(c.count);let offset=0;for(const chunk of c.chunks){samples.set(chunk,offset);offset+=chunk.length;}const audio=encodeWave(samples,c.context.sampleRate);nativePending.current=true;await invoke('whisper_start',{...settings,audio,prompt:names.map(n=>n.slice(0,60)).join(', ')});if(id!==token.current){await invoke('whisper_stop');setPhase('idle');return;}void poll(id);}catch(e){setPhase('idle');if(id===token.current)setError(String(e));}finally{nativePending.current=false;}}
 async function start(options:{autoEnd?:boolean}={}){if(phase!=='idle'||nativePending.current)return;const id=++token.current;let ownedStream:MediaStream|undefined,ownedContext:AudioContext|undefined;setError('');setPhase('starting');try{await invoke('whisper_check',{...settings});if(id!==token.current)return;const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true},video:false});ownedStream=stream;if(id!==token.current){stream.getTracks().forEach(t=>t.stop());return;}const context=new AudioContext();ownedContext=context;await context.resume();if(id!==token.current){stream.getTracks().forEach(t=>t.stop());await context.close();return;}const source=context.createMediaStreamSource(stream),node=context.createScriptProcessor(4096,1,1);const c={stream,context,source,node,chunks:[] as Float32Array[],count:0};const endpoint=new SpeechEndpoint();capture.current=c;meter.current={started:performance.now(),level:0};node.onaudioprocess=e=>{meter.current.level=microphoneLevel(e.inputBuffer.getChannelData(0));const remaining=Math.floor(context.sampleRate*15)-c.count;if(remaining>0){const chunk=e.inputBuffer.getChannelData(0).slice(0,remaining);c.chunks.push(chunk);c.count+=chunk.length;}if(options.autoEnd){const chunk=e.inputBuffer.getChannelData(0);let energy=0;for(const sample of chunk)energy+=sample*sample;const decision=endpoint.step(Math.sqrt(energy/chunk.length),chunk.length/context.sampleRate*1000);if(decision==='finish')void finish();else if(decision==='silence'){void cancel();setError('No speech detected. Hands-free stopped; try again when ready.');}}};source.connect(node);node.connect(context.destination);setPhase('recording');timer.current=setTimeout(()=>void finish(),15000);}catch(e){ownedStream?.getTracks().forEach(t=>t.stop());if(ownedContext&&ownedContext.state!=='closed')void ownedContext.close();if(id===token.current){release();setPhase('idle');setError(String(e));}}}
 return {elapsed,level,settings,setSettings:(value:typeof settings)=>{setSettings(value);saveWhisper(value);},phase,error,start,finish,cancel};
}
