import {readStored,writeStored} from './persistence';
export interface WhisperSettings{exePath:string;modelPath:string}
export const DEFAULT_WHISPER:WhisperSettings={exePath:'C:/AI/ManaAI-CV-2/data/whisper/runtime/Release/whisper-cli.exe',modelPath:'C:/AI/ManaAI-CV-2/data/whisper/ggml-small.en.bin'};
export function validateWhisper(value:unknown):WhisperSettings{const v=value&&typeof value==='object'?value as Record<string,unknown>:{};return {exePath:typeof v.exePath==='string'&&v.exePath.length<=1000?v.exePath:DEFAULT_WHISPER.exePath,modelPath:typeof v.modelPath==='string'&&v.modelPath.length<=1000?v.modelPath:DEFAULT_WHISPER.modelPath};}
export function loadWhisper(){try{return validateWhisper(JSON.parse(readStored('mana.whisper.v1')??'null'));}catch{return {...DEFAULT_WHISPER};}}
export function saveWhisper(settings:WhisperSettings){writeStored('mana.whisper.v1',JSON.stringify(validateWhisper(settings)));}
export function encodeWave(samples:Float32Array,sampleRate:number):number[]{if(!Number.isFinite(sampleRate)||sampleRate<16000||sampleRate>192000||!samples.length||samples.length>sampleRate*15)throw Error('Record up to 15 seconds of audio.');const count=Math.floor(samples.length*16000/sampleRate);if(count<1600)throw Error('Recording is too short.');const buffer=new ArrayBuffer(44+count*2),view=new DataView(buffer);const str=(offset:number,text:string)=>{for(let i=0;i<text.length;i++)view.setUint8(offset+i,text.charCodeAt(i));};str(0,'RIFF');view.setUint32(4,36+count*2,true);str(8,'WAVE');str(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,16000,true);view.setUint32(28,32000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,count*2,true);let energy=0;for(let i=0;i<count;i++){const start=Math.floor(i*sampleRate/16000),end=Math.min(samples.length,Math.max(start+1,Math.floor((i+1)*sampleRate/16000)));let sum=0;for(let j=start;j<end;j++)sum+=Number.isFinite(samples[j])?samples[j]:0;const sample=Math.max(-1,Math.min(1,sum/(end-start)));energy+=sample*sample;view.setInt16(44+i*2,Math.round(sample*(sample<0?32768:32767)),true);}if(Math.sqrt(energy/count)<0.003)throw Error('Recording is too quiet. Check your input device and try again.');return Array.from(new Uint8Array(buffer));}

/** Display-only RMS meter; it is not a speech detector or accuracy score. */
export function microphoneLevel(samples:Float32Array):number{let energy=0;for(const value of samples)if(Number.isFinite(value))energy+=value*value;const rms=Math.sqrt(energy/Math.max(1,samples.length));return rms<=0?0:Math.max(0,Math.min(1,(20*Math.log10(rms)+60)/60));}
