use std::process::{Child,Command,Stdio};
use std::sync::Mutex;
use std::time::{Duration,Instant};
use std::io::Write;
#[derive(Default)]
pub struct Dictation(pub Mutex<Option<(Child,Instant)>>);
fn command(script:&str)->Command{let mut cmd=Command::new("powershell.exe");cmd.args(["-NoProfile","-NonInteractive","-Command",script]);#[cfg(windows)] {use std::os::windows::process::CommandExt;cmd.creation_flags(0x08000000);}cmd}
const SCRIPT:&str=r#"$ErrorActionPreference='Stop'; [Console]::InputEncoding=[System.Text.UTF8Encoding]::new(); [Console]::OutputEncoding=[System.Text.UTF8Encoding]::new(); Add-Type -AssemblyName System.Speech; $r=$null; try { $p=[Console]::In.ReadToEnd() | ConvertFrom-Json; $r=[System.Speech.Recognition.SpeechRecognitionEngine]::new([string]$p.id); $r.LoadGrammar([System.Speech.Recognition.DictationGrammar]::new()); $phrases=[System.Collections.Generic.List[string]]::new(); foreach($name in @($p.names)) { if($name){$phrases.Add([string]$name);foreach($greeting in @('Hello','Hi','Hey')){$phrases.Add($greeting+' '+[string]$name)}} }; $phrases.Add('Hello'); if($phrases.Count -gt 0){$choices=[System.Speech.Recognition.Choices]::new($phrases.ToArray());$builder=[System.Speech.Recognition.GrammarBuilder]::new($choices);$builder.Culture=$r.RecognizerInfo.Culture;$grammar=[System.Speech.Recognition.Grammar]::new($builder);$grammar.Name='Companion names and greetings';$r.LoadGrammar($grammar)}; $r.SetInputToDefaultAudioDevice(); $r.BabbleTimeout=[TimeSpan]::FromSeconds(10); $result=$r.Recognize([TimeSpan]::FromSeconds(8)); if($null -eq $result){ @{text='';error='No speech recognized. Check your microphone and try again.'} | ConvertTo-Json -Compress } else { @{text=$result.Text;confidence=$result.Confidence;alternatives=@($result.Alternates | Select-Object -First 4 | ForEach-Object { $_.Text });error=''} | ConvertTo-Json -Compress } } catch { @{text='';error='Windows could not listen. Check microphone privacy permissions, default input device and installed speech language.'} | ConvertTo-Json -Compress } finally { if($null -ne $r){$r.Dispose()} }"#;
#[tauri::command]
pub async fn dictation_languages()->Result<serde_json::Value,String>{tauri::async_runtime::spawn_blocking(||{let output=command("$ErrorActionPreference='Stop'; [Console]::OutputEncoding=[System.Text.UTF8Encoding]::new(); Add-Type -AssemblyName System.Speech; $items=@([System.Speech.Recognition.SpeechRecognitionEngine]::InstalledRecognizers() | ForEach-Object { @{id=$_.Id;name=$_.Name;language=$_.Culture.Name} }); ConvertTo-Json -InputObject $items -Compress").output().map_err(|e|e.to_string())?;if !output.status.success(){return Err("Installed Windows speech recognizers could not be loaded.".into())}serde_json::from_slice(&output.stdout).map_err(|e|e.to_string())}).await.map_err(|e|e.to_string())?}
pub fn stop(state:&Dictation)->Result<(),String>{if let Some((mut child,_))=state.0.lock().map_err(|e|e.to_string())?.take(){let _=child.kill();let _=child.wait();}Ok(())}
#[tauri::command]
pub fn dictation_stop(state:tauri::State<Dictation>)->Result<(),String>{stop(&state)}
fn validate_id(id:&str)->Result<(),String>{if id.trim().is_empty()||id.len()>500{Err("Choose an installed speech language.".into())}else{Ok(())}}
fn validate_names(names:&[String])->Result<(),String>{if names.len()>2||names.iter().any(|n|n.trim().is_empty()||n.chars().count()>60){Err("Use up to two names under 60 characters.".into())}else{Ok(())}}
#[tauri::command]
pub fn dictation_start(state:tauri::State<Dictation>,id:String,names:Vec<String>)->Result<(),String>{validate_id(&id)?;validate_names(&names)?;let mut slot=state.0.lock().map_err(|e|e.to_string())?;if slot.is_some(){return Err("Dictation is already active.".into())}let mut child=command(SCRIPT).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::null()).spawn().map_err(|e|e.to_string())?;let data=serde_json::to_vec(&serde_json::json!({"id":id,"names":names})).map_err(|e|e.to_string())?;let sent=child.stdin.take().ok_or("Dictation input unavailable".to_string()).and_then(|mut input|input.write_all(&data).map_err(|e|e.to_string()));if let Err(e)=sent{let _=child.kill();let _=child.wait();return Err(e)}*slot=Some((child,Instant::now()));Ok(())}
#[tauri::command]
pub fn dictation_poll(state:tauri::State<Dictation>)->Result<serde_json::Value,String>{let mut slot=state.0.lock().map_err(|e|e.to_string())?;let Some((child,started))=slot.as_mut() else{return Ok(serde_json::json!({"done":true,"text":"","error":"Dictation stopped."}))};if started.elapsed()>Duration::from_secs(30){let (mut child,_)=slot.take().unwrap();let _=child.kill();let _=child.wait();return Ok(serde_json::json!({"done":true,"text":"","error":"Listening timed out. Try a shorter phrase."}))}if child.try_wait().map_err(|e|e.to_string())?.is_none(){return Ok(serde_json::json!({"done":false}))}let (child,_)=slot.take().unwrap();let output=child.wait_with_output().map_err(|e|e.to_string())?;let result:serde_json::Value=serde_json::from_slice(&output.stdout).map_err(|_|"Windows dictation returned no result. Check your speech language and microphone.".to_string())?;Ok(serde_json::json!({"done":true,"text":result["text"],"error":result["error"],"confidence":result["confidence"],"alternatives":result["alternatives"]}))}
#[cfg(test)] mod tests{use super::*;#[test]fn rejects_missing_or_oversize_language(){assert!(validate_id("").is_err());assert!(validate_id(&"x".repeat(501)).is_err());assert!(validate_id("MS-1033-80-DESK").is_ok());}#[test]fn stopping_idle_dictation_is_safe(){stop(&Dictation::default()).unwrap();}}

#[cfg(test)] mod tuning_tests{use super::*;#[test]fn bounded_names_are_data(){assert!(validate_names(&vec!["Mana".into(),"Aishi".into()]).is_ok());assert!(validate_names(&vec!["x".repeat(61)]).is_err());assert!(validate_names(&vec!["a".into();3]).is_err());}}
