use std::{fs,path::{Path,PathBuf},process::{Child,Command,Stdio},sync::Mutex,time::{Instant,Duration}};
use tauri::Manager;
struct Session{child:Child,path:PathBuf,started:Instant}
impl Drop for Session{fn drop(&mut self){let _=self.child.kill();let _=self.child.wait();let _=fs::remove_file(&self.path);let _=fs::remove_file(self.path.with_extension("txt"));}}
#[derive(Default)]pub struct Whisper(Mutex<Option<Session>>);
fn check(exe:&str,model:&str)->Result<(),String>{if !Path::new(exe).is_file()||!Path::new(model).is_file(){return Err("Choose an existing whisper-cli executable and GGML model in Whisper setup.".into())}Ok(())}
#[tauri::command]pub fn whisper_check(exe_path:String,model_path:String)->Result<(),String>{check(&exe_path,&model_path)}
pub fn stop(state:&Whisper)->Result<(),String>{state.0.lock().map_err(|e|e.to_string())?.take();Ok(())}
#[tauri::command]pub fn whisper_stop(state:tauri::State<Whisper>)->Result<(),String>{stop(&state)}
fn validate_wave(audio:&[u8])->Result<(),String>{if audio.len()<3244||audio.len()>480044||audio.get(0..4)!=Some(b"RIFF")||audio.get(8..16)!=Some(b"WAVEfmt ")||audio.get(36..40)!=Some(b"data"){return Err("Expected 16 kHz mono PCM WAV, up to 15 seconds.".into())}let u16at=|p|u16::from_le_bytes([audio[p],audio[p+1]]);let u32at=|p|u32::from_le_bytes([audio[p],audio[p+1],audio[p+2],audio[p+3]]);if u32at(4) as usize!=audio.len()-8||u32at(16)!=16||u16at(20)!=1||u16at(22)!=1||u32at(24)!=16000||u32at(28)!=32000||u16at(32)!=2||u16at(34)!=16||u32at(40) as usize!=audio.len()-44||(audio.len()-44)%2!=0{return Err("Invalid WAV audio format.".into())}let energy: f64=audio[44..].chunks_exact(2).map(|b|{let v=i16::from_le_bytes([b[0],b[1]]) as f64/32768.0;v*v}).sum();if (energy/((audio.len()-44)/2) as f64).sqrt()<0.003{return Err("Recording is too quiet. Check the microphone.".into())}Ok(())}
#[tauri::command]pub fn whisper_start(app:tauri::AppHandle,state:tauri::State<Whisper>,exe_path:String,model_path:String,audio:Vec<u8>,prompt:String)->Result<(),String>{check(&exe_path,&model_path)?;validate_wave(&audio)?;if prompt.len()>500{return Err("Name prompt is too long.".into())}let mut slot=state.0.lock().map_err(|e|e.to_string())?;if slot.is_some(){return Err("Transcription already running.".into())}let dir=app.path().app_data_dir().map_err(|e|e.to_string())?.join("transcription-temp");fs::create_dir_all(&dir).map_err(|e|e.to_string())?;let unique=std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map_err(|e|e.to_string())?.as_nanos();let path=dir.join(format!("clip-{unique}.wav"));fs::write(&path,audio).map_err(|e|e.to_string())?;let mut cmd=Command::new(exe_path);cmd.args(["-m",&model_path,"-f"]).arg(&path).args(["-l","en","-ng","-nt","-otxt","-of"]).arg(path.with_extension("")).args(["--prompt",&prompt,"-t","4"]).stdout(Stdio::null()).stderr(Stdio::null());#[cfg(windows)]{use std::os::windows::process::CommandExt;cmd.creation_flags(0x08000000);}match cmd.spawn(){Ok(child)=>{*slot=Some(Session{child,path,started:Instant::now()});Ok(())},Err(e)=>{let _=fs::remove_file(path);Err(e.to_string())}}}
#[tauri::command]pub fn whisper_poll(state:tauri::State<Whisper>)->Result<serde_json::Value,String>{let mut slot=state.0.lock().map_err(|e|e.to_string())?;let session=slot.as_mut().ok_or("Transcription stopped.")?;if session.started.elapsed()>Duration::from_secs(180){slot.take();return Err("Whisper transcription timed out.".into())}let status=match session.child.try_wait().map_err(|e|e.to_string())?{None=>return Ok(serde_json::json!({"done":false})),Some(status)=>status};let session=slot.take().unwrap();if !status.success(){return Err("Whisper failed. Check the executable/model pair and try again.".into())}let bytes=fs::read(session.path.with_extension("txt")).map_err(|e|e.to_string())?;if bytes.len()>20000{return Err("Transcription output is too long.".into())}let text=String::from_utf8(bytes).map_err(|e|e.to_string())?.trim().to_string();if text.is_empty(){return Err("No speech recognized.".into())}Ok(serde_json::json!({"done":true,"text":text}))}
#[cfg(test)]mod tests{use super::*;#[test]fn rejects_invalid_and_silent_audio(){assert!(validate_wave(&[]).is_err());assert!(validate_wave(&vec![0;500000]).is_err());}#[test]fn idle_stop_is_safe(){stop(&Whisper::default()).unwrap();}}

#[cfg(test)]mod audio_tests{use super::*;
fn wave()->Vec<u8>{let mut v=vec![0u8;3244];v[0..4].copy_from_slice(b"RIFF");v[4..8].copy_from_slice(&3236u32.to_le_bytes());v[8..16].copy_from_slice(b"WAVEfmt ");v[16..20].copy_from_slice(&16u32.to_le_bytes());v[20..22].copy_from_slice(&1u16.to_le_bytes());v[22..24].copy_from_slice(&1u16.to_le_bytes());v[24..28].copy_from_slice(&16000u32.to_le_bytes());v[28..32].copy_from_slice(&32000u32.to_le_bytes());v[32..34].copy_from_slice(&2u16.to_le_bytes());v[34..36].copy_from_slice(&16u16.to_le_bytes());v[36..40].copy_from_slice(b"data");v[40..44].copy_from_slice(&3200u32.to_le_bytes());for b in v[44..].chunks_exact_mut(2){b.copy_from_slice(&8000i16.to_le_bytes());}v}
#[test]fn validates_audio_format_and_detects_silence(){let mut v=wave();validate_wave(&v).unwrap();v[24..28].copy_from_slice(&48000u32.to_le_bytes());assert!(validate_wave(&v).is_err());let mut v=wave();v[44..].fill(0);assert!(validate_wave(&v).is_err());let mut v=wave();v.pop();assert!(validate_wave(&v).is_err());}
#[test]fn dropped_session_removes_temporary_audio_and_transcript(){let path=std::env::temp_dir().join(format!("mana-whisper-cleanup-{}.wav",std::process::id()));fs::write(&path,b"temporary").unwrap();fs::write(path.with_extension("txt"),b"text").unwrap();let child=Command::new("powershell.exe").args(["-NoProfile","-NonInteractive","-Command","exit 0"]).stdout(Stdio::null()).spawn().unwrap();drop(Session{child,path:path.clone(),started:Instant::now()});assert!(!path.exists());assert!(!path.with_extension("txt").exists());}
}
